version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
    rust: "1.70"
  commands:
    # Cancel building pull requests when they do not change pybigtools.
    #
    # If there are no changes (git diff exits with 0) we force the command to return with 183.
    # This is a special exit code on Read the Docs that will cancel the build immediately.
    - |
      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/master -- pybigtools/ .readthedocs.yaml;
      then
        exit 183;
      fi
    # Install dependencies
    - pip install pdoc
    - pip install pybigtools/
    # Build the site
    - pdoc -o pybigtools/html pybigtools
    # Copy generated files into Read the Docs directory
    - mkdir --parents _readthedocs/html/
    - cp --recursive pybigtools/html/* _readthedocs/html/
